name: Terraform Azure Deployement
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform code Deployement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init