name: Terraform Azure Deployement
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform code Deployement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4